#FROM python:3
#RUN pip install django==3.2

#COPY . .

#RUN python manage.py migrate
#EXPOSE 8000
#CMD ["python","manage.py","runserver","0.0.0.0:8000"]
FROM python:3.10-slim

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir django==3.2

RUN python manage.py migrate

EXPOSE 8000

CMD ["python","manage.py","runserver","0.0.0.0:8000"]

